[tool.poetry]
name = "refactor-challenge"
version = "0.0.1"
description = "Legacy code refactoring challenge"
authors = ["Bart van Es"]
packages = [{ include = "legacy" }]
readme = "README.md"
repository = "https://github.com/TABVE/refactoring_challenge"